// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoxlZtte52qL5Mr29kUGNk_2zQghFcIjI',
    appId: '1:172752432223:web:aa6f5c3820e59ca35a3fea',
    messagingSenderId: '172752432223',
    projectId: 'mage-e180d',
    authDomain: 'mage-e180d.firebaseapp.com',
    storageBucket: 'mage-e180d.appspot.com',
    measurementId: 'G-ZK7MHQ4CJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-YkN3IkoMtz2bdWpujTmVap6QmTqWU8',
    appId: '1:172752432223:android:3142c6dc7a14aa0e5a3fea',
    messagingSenderId: '172752432223',
    projectId: 'mage-e180d',
    storageBucket: 'mage-e180d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOWgOR1PaIoYqFy2dm7VXxfwhNv6F1s5I',
    appId: '1:172752432223:ios:4ee3d06acf65aa4e5a3fea',
    messagingSenderId: '172752432223',
    projectId: 'mage-e180d',
    storageBucket: 'mage-e180d.appspot.com',
    androidClientId:
        '172752432223-586453kj3fldcdidkcrj1t8a8abi91on.apps.googleusercontent.com',
    iosClientId:
        '172752432223-eudpqel0velf7nc1ptmt8afsuellrbcs.apps.googleusercontent.com',
    iosBundleId: 'com.artmage.mage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOWgOR1PaIoYqFy2dm7VXxfwhNv6F1s5I',
    appId: '1:172752432223:ios:3212b9c5b0d8ecb85a3fea',
    messagingSenderId: '172752432223',
    projectId: 'mage-e180d',
    storageBucket: 'mage-e180d.appspot.com',
    androidClientId:
        '172752432223-586453kj3fldcdidkcrj1t8a8abi91on.apps.googleusercontent.com',
    iosClientId:
        '172752432223-cqoot9kkglkk11h6fp60ltak31l11432.apps.googleusercontent.com',
    iosBundleId: 'com.artmage.mage.RunnerTests',
  );
}
